# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.9.2
_src_path: gh:algorandfoundation/algokit-beaker-default-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: conwuliri@gmail.com
author_name: Emeka Onwuliri
contract_name: derivative
deployment_language: python
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
preset_name: production
project_name: Constellation-algo
python_linter: ruff
use_dispenser: false
use_github_actions: true
use_pre_commit: true
use_python_black: true
use_python_mypy: true
use_python_pip_audit: true
use_python_pytest: true

